name: mockapi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  infinite_scroll_pagination: ^4.1.0
  json_theme_plus: ^6.7.3
  provider: ^6.1.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/theme/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
